# Generated by Django 4.0.1 on 2022-02-06 14:33

import bot.models
import bot.types
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('radius', models.PositiveIntegerField(default=5, verbose_name='Радиус, км')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создан, по UTC')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Локация')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('times', models.CharField(max_length=512, verbose_name='Время')),
                ('message_id', models.PositiveIntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=4096, null=True, verbose_name='Текст')),
                ('photo', models.CharField(default=None, max_length=2048, null=True, verbose_name='Фото')),
                ('video', models.CharField(default=None, max_length=2048, null=True, verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создано')),
                ('status', models.CharField(choices=[('WAIT', '⏳ Ожидание'), ('SEND', '📨 Отправка'), ('DONE', '🎫 Готово')], default='WAIT', max_length=4, verbose_name='Статус')),
                ('photo_id', models.CharField(blank=True, help_text='Указывается по FileID, его можно получить отправив боту нужное вам фото.', max_length=128, null=True, verbose_name='Фото')),
                ('gif_id', models.CharField(blank=True, help_text='Указывается по FileID, его можно получить отправив боту нужное вам gif.', max_length=128, null=True, verbose_name='GIF')),
                ('video_id', models.CharField(blank=True, help_text='Указывается по FileID, его можно получить отправив боту нужное вам видео.', max_length=128, null=True, verbose_name='Видео')),
                ('message', models.TextField(max_length=1024, verbose_name='Сообщение')),
                ('preview', models.BooleanField(default=True, verbose_name='Превью')),
                ('button', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кнопка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('receivers', models.IntegerField(blank=True, null=True, verbose_name='Получатели')),
                ('user_type', models.CharField(blank=True, choices=[('CLIENT', 'Клиент'), ('MASTER', 'Мастер')], default=None, max_length=8, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('media_chat_link', models.URLField(default='-', max_length=64, verbose_name='Ссылка на чат медиа')),
                ('portfolio_chat_link', models.URLField(default='-', max_length=64, verbose_name='Ссылка на чат портфолио')),
                ('media_chat_id', models.BigIntegerField(default=0, verbose_name='ID чата медиа')),
                ('portfolio_chat_id', models.BigIntegerField(default=0, verbose_name='ID чата портфолио')),
                ('hint_media_id', bot.types.MediaField(default='-', max_length=128, verbose_name='Медиа файл подсказки')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'списки',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'суб-категория',
                'verbose_name_plural': 'суб-категории',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создан, по UTC')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='@юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('type', models.CharField(choices=[('CLIENT', 'Клиент'), ('MASTER', 'Мастер')], default=None, max_length=8, null=True, verbose_name='Тип')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), geography=True, srid=4326, verbose_name='Локация')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Бан')),
                ('state', models.CharField(default=None, max_length=256, null=True)),
                ('state_data', models.TextField(default=None, max_length=16384, null=True)),
                ('categories', models.ManyToManyField(default=None, to='bot.Subcategory', verbose_name='Суб-категории')),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.city', verbose_name='Город')),
                ('portfolio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.portfolio', verbose_name='Портфолио')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создан, по UTC')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('currency', models.CharField(max_length=16, verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создан, по UTC')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Мастер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'отклики',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='bot.user', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='bot.user', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='order',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subcategory', verbose_name='Суб-категория'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='🕐 Создан, по UTC')),
                ('type', models.CharField(choices=[('TEXT', '🅰️ Текст'), ('REPLY_BUTTON', '⏹ Reply-кнопка'), ('INLINE_BUTTON', '⏺ Inline-кнопка'), ('COMMAND', '✳️ Команда')], max_length=16, verbose_name='Тип')),
                ('content', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Контент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.country'),
        ),
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot.category', bot.models.Stats),
        ),
        migrations.CreateModel(
            name='OrderStats',
            fields=[
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot.order', bot.models.Stats),
        ),
        migrations.CreateModel(
            name='RequestStats',
            fields=[
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot.request', bot.models.Stats),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot.user', bot.models.Stats),
        ),
    ]
