# Generated by Django 4.0.1 on 2022-02-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='hint_media_id',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='message_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
