# Generated by Django 4.0.3 on 2022-03-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='price',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.country', verbose_name='Страна'),
        ),
    ]
