# Generated by Django 4.0.3 on 2022-03-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_settings_price_alter_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
