# Generated by Django 4.0.4 on 2022-06-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_request_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_active_master',
        ),
        migrations.AddField(
            model_name='settings',
            name='client_freeze_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма списания с клиента, грн'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='-', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_client',
            field=models.BooleanField(default=False, verbose_name='Активен клиент'),
        ),
    ]
