# Generated by Django 4.0.6 on 2022-07-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_user_is_active_settings_client_freeze_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='client_freeze_amount',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_master',
            field=models.BooleanField(default=False, verbose_name='Активен мастер'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео')], max_length=8)),
                ('file_id', models.CharField(max_length=128)),
                ('file_url', models.URLField(default=None, max_length=1024, null=True)),
                ('url_created', models.DateTimeField(default=None, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.portfolio', verbose_name='Портфолио')),
            ],
        ),
    ]
