# Generated by Django 4.0.6 on 2022-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_settings_client_freeze_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='video',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='portfolio_chat_id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='portfolio_chat_link',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAIT', '⏳ Ожидание'), ('FOUND', '✅ Мастер найден'), ('NOT_FOUND', '❌ Мастер не найден'), ('CANCELED', '❎ Не актуально')], default='WAIT', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=16, null=True, verbose_name='Телефон'),
        ),
    ]
